import Head from "next/head";
import { Box, Text, Flex, Spacer, Button, Image } from "@chakra-ui/react";
import bgStyles from "@/styles/BgImage.module.css";

import SignupForm from "@/pages/components/SIgnupForm";
import ModalBox from "./components/ModalBox";
import { roboto } from "./font";

export default function Home() {
  const modalBoxContent = [
    {
      title: "Unparalleled Decentralization",
      paragraph:
        "Our EVM Rollup solution takes decentralization to new heights, surpassing other Layer 2 (L2) solutions in the market. By harnessing the power of the Tezos blockchain, we ensure that your applications and app-chains remain truly decentralized, transparent, and resilient.",
    },
    {
      title: "Versatility and Flexibility",
      paragraph:
        "Whether you're envisioning an open decentralized platform or a private app-chain, Etherlink provides the perfect foundation. With its versatile architecture, you can create tailored solutions that fit your unique business requirements and user needs.",
    },
    {
      title: "Scalability and Speed",
      paragraph:
        "Leave scalability concerns behind as Etherlink leverages the Tezos network's inherent scalability. Enjoy lightning-fast transaction processing and a seamless user experience, enabling you to handle high volumes of transactions with ease.",
    },
  ];

  return (
    <>
      <Head>
        <title>Etherlink</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Box
        p={{
          base: "25px 16px 70px 16px",
          md: "30px 50px 100px 50px",
          xl: "40px 81px 150px 81px",
        }}
        className={bgStyles.bgUpperImage}
      >
        <Flex align="center">
          <Text
            fontSize={{ base: "24px", md: "28px", xl: "32px" }}
            fontWeight="700"
          >
            Etherlink
          </Text>
          <Spacer />
          <Flex>
            <Text alignSelf="center" fontSize="12px" pr="5px">
              Powered by
            </Text>
            <Image
              w={{ base: "70px", md: "85px", xl: "100px" }}
              src="/tezos-xtz-seeklogo.svg"
              alt="tezos logo"
            />
          </Flex>
        </Flex>

        <Flex mt="20%" direction={{ base: "column", md: "row" }} gap="20px">
          <Box maxW="700px">
            <Text
              fontSize={{ base: "30px", md: "60px", xl: "90px" }}
              lineHeight="110%"
              fontWeight="450"
            >
              The Future <br />
              of Ethereum <br />
              L2 Solutions
            </Text>
            <Text
              fontSize={{ base: "16px", md: "20px", xl: "24px" }}
              maxW="630px"
              pt="3%"
              className={roboto.className}
            >
              Built on the robust Tezos blockchain, Etherlink empowers
              businesses and developers to create a new era of open, secure, and
              scalable applications.
            </Text>
          </Box>
          <Spacer />
          <SignupForm />
        </Flex>
      </Box>

      <Box
        pt={{ base: "60px", md: "80px", xl: "104px" }}
        pb={{ base: "80px", md: "120px", xl: "164px" }}
        bg="#04001C"
      >
        <Text
          align="center"
          fontSize={{ base: "24px", md: "32px", xl: "48px" }}
          color="white"
        >
          Why Choose Etherlink?
        </Text>
        <Text
          align="center"
          fontSize={{ base: "16px", md: "20px", xl: "24px" }}
          color="white"
        >
          Be at the forefront of decentralized innovation
        </Text>
        <Flex
          justify="space-around"
          wrap="wrap"
          gap="20px"
          mt={{ base: "40px", md: "60px", xl: "80px" }}
          p={{ base: "0px 16px", xl: "0px 30px" }}
        >
          {modalBoxContent?.map((content, index) => (
            <ModalBox
              key={index}
              title={content.title}
              paragraph={content.paragraph}
            />
          ))}
        </Flex>
      </Box>

      <Box className={bgStyles.bgBottomImage}>
        <Flex
          direction="column"
          align="center"
          p={{
            base: "50px 16px 150px 16px",
            md: "75px 50px 175px 50px",
            xl: "100px 90px 200px 90px",
          }}
        >
          <Text
            fontWeight="450"
            fontSize={{ base: "28px", md: "45px", xl: "60px" }}
            align="center"
            lineHeight="100%"
          >
            Join the Etherlink <br /> Revolution
          </Text>
          <Text
            fontSize={{ base: "14px", md: "20px", xl: "24px" }}
            w={{ base: "288px", md: "400px", xl: "700px" }}
            mt="20px"
            className={roboto.className}
          >
            Together, let's shape the future of decentralized applications and
            unleash the true power of the Tezos blockchain. Enter your email
            above and be the first to know when Etherlink goes live.
          </Text>
          <Button
            bg="#003BE8"
            color="#FFFFFF"
            p="12px 40px"
            mt="20px"
            borderRadius="75px"
          >
            Sign up
          </Button>
        </Flex>
        <Text
          fontSize={{ base: "16px", xl: "18px" }}
          p="0px 0px 20px 15px"
          className={roboto.className}
        >
          © Etherlink 2023
        </Text>
      </Box>
    </>
  );
}
