import Head from "next/head";
import Image from "next/image";
import { Box, Text, Flex, Spacer } from "@chakra-ui/react";
import SignupForm from "@/pages/components/SIgnupForm";
import bgStyles from "@/styles/BgImage.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Etherlink</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Box pl="81px" pr="81px" pb="197px">
        <Image
          src="/bg-upper.png"
          alt="bg-image"
          fill={true}
          objectFit="cover"
          className={bgStyles.bgUpperImage}
        />
        <Flex align="center">
          <Text fontSize="32px" fontWeight="700">
            Etherlink
          </Text>
          <Spacer />
          <Flex>
            <Text fontSize="12px" pr="2" pt="2">
              Powered by
            </Text>
            <img src="/tezos-xtz-seeklogo.svg" alt="tezos logo" />
          </Flex>
        </Flex>

        <Flex mt="20%">
          <Box maxW="700px">
            <Text fontSize="90px" lineHeight="100%">
              The Future <br />
              of Ethereum <br />
              L2 Solutions
            </Text>
            <Text maxW="630px" pt="3%">
              Built on the robust Tezos blockchain, Etherlink empowers
              businesses and developers to create a new era of open, secure, and
              scalable applications.
            </Text>
          </Box>
          <Spacer />
          <SignupForm />
        </Flex>
      </Box>
      <Box></Box>
      <Box></Box>
    </>
  );
}
